name: Update nursery data (monthly)

on:
  schedule:
    # JST 09:30 on the 2nd day of every month（必要に応じて調整）
    - cron: "30 0 2 * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Update data
        run: |
          python scripts/update_from_yokohama.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.json
          git add data/master_facilities.csv || true
          git commit -m "Update nursery data" || echo "No changes"
          git push
